# configure RabbitMQ parameters 
[rabbit]
user = "guest"
address =  "127.0.0.1"
port = 5672
queue = "default"

# parameters for mock time
[time]
stepsize = 100 #[s]
start = 0 # [h]
end = 24 # [h]
day = 100 # [d] day of year
year = 2020 # [a] present year
