# configure RabbitMQ parameters 
[rabbit]
user = "guest"
address =  "127.0.0.1"
port = 5672
queue = "metering"

# parameters for mock time
[time]
stepsize = 300 # in [s]
start = 0 # [h]
end = 24 # [h]
day = 100 # [d] day of year
year = 2020 # [a] present year

#parameters to 
[panel]
alignment = 180 # [deg] 180 is south
inclination = 30 # [deg] angle from horizontal
peak = 10 # nominal power of PV panels [kW]
efficiency = 0.12 # ratio electric output to photonic input
